### ISSUE TITLE
remove language tags while only single language

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#1]
Need to remove the language from header and footer when only a single language available.

**Comment by MortenHofft** [comment]
Let me know if you need any help. Do you plan to have any translations? 
I've disconnected the danish home page as an example showing how pages are linked. You can also see some documentation https://hp-theme.gbif-staging.org/translations

**Comment by AaronWilton** [comment]
Hi Morten
Yes we will eventually have two languages (en, mi), but I currently do not have access anyone to do the maori versions.

**Comment by MortenHofft** [comment]
There is 2 options for having multiple languages.

One is to have a default language. Say english for `https://hp-new-zealand.gbif-staging.org/` and then have maori on `https://hp-new-zealand.gbif-staging.org/mi`.
Example here https://hp-theme.gbif-staging.org/ (english and latin)

Another approach is to have a language selector on `https://hp-new-zealand.gbif-staging.org/` and then serve english from `https://hp-new-zealand.gbif-staging.org/en` and maori from `https://hp-new-zealand.gbif-staging.org/mi`
Example here https://hp-canadian-biodiversity.gbif-staging.org/ (english and french)

Do you have a preference and would you like me to set it up (with maori) despite you not having a translator yet?

**Comment by AaronWilton** [comment]
Have removed the language content in the footer (languages.yml & translations.yml) so the languages don't show until they are available.
