### ISSUE TITLE
Navigation on home page from statistics - open in a new window

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#16]
**Is your feature request related to a problem? Please describe.**
The statistics on the home page act as a hyperlink to to pages within the hosted site or to GBIF site.  When it is the GBIF site the user therefore looses the hosted-node website.  It would be more polite if this used target=_blank

In the nz site this is happening for "Publishers" and "Data sets"

**Describe the solution you'd like**
Configure the hyperlinks so that when the link goes to to a different website, it uses a new window/tab (target="_blank") somehow.

Apologies if this is already possible & i have missed it in the documentation.

**Describe alternatives you've considered**
Have pages within the hosted site that display the content rather than taking people to the GBIF site. (but lower priority - i think the link to the main site is fine as long as it is in a new window/tab)

**Comment by MortenHofft** [comment]
Hi
**Target blank**
Personally I do not like when sites open new tabs or windows for me (I press command when I want to). It isn't how links in general works either. But that said, it is a reasonable request. It isn't possible just now, but I can add that option.

In Jekyll in general you would do it with markdown or writing html, but obviously that wouldn't work in this case where the `href` is a separate field. As a workaround you could remove the `href` in https://github.com/gbif/hp-new-zealand/blob/master/_data/home.yml and add an `<a>` tag around the title with the target set to blank. But it would behave slightly different in that the image wouldn't link for example.
https://talk.jekyllrb.com/t/how-can-i-ensure-my-links-open-in-a-new-tab/4318

**Publisher and datasets**
You can add those to your site if you wish to, but detail pages about individual datasets/publishers will still link to GBIF.org
https://hp-theme.gbif-staging.org/publisher/search
https://hp-theme.gbif-staging.org/dataset/search

Hope that helps

**Comment by MortenHofft** [comment]
I've created an issue for "force open in new tab" https://github.com/gbif/hosted-portals/issues/234

**Comment by MortenHofft** [comment]
You can now add `blankTarget: true`

**Comment by AaronWilton** [comment]
@MortenHofft  - thanks!
