### ISSUE TITLE
Occurrences not showing on map

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#19]
**Describe the bug**
The occurrence records are no longer showing on the map in the portal.

**To Reproduce**
data -> map

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- windows
- edge

**Smartphone (please complete the following information):**
 - laptop
also occurring on other peoples devices and different browsers.

**Additional context**

**Comment by MortenHofft** [comment]
That indeed look like a bug. I'll look into it. Thanks

**Comment by MortenHofft** [comment]
That is my who did a bad initial configuration of your site. 

The parameter was never intended to be `countryCode` but simply `country`. I have mistakenly allowed both, but only one works with the maps
https://github.com/gbif/hp-new-zealand/commit/6459bfd9963b775ccdba70050124f0c00654019e

It is now fixed

**Comment by MortenHofft** [comment]
I've added a default map focus
https://github.com/gbif/hp-new-zealand/commit/f0d0424c559cc1bbd2e34dff3b5096e9c7804352
