### ISSUE TITLE
Add statistics to home page

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#2]
Have added some configuration to home.yml
Investigate why not showing.

**Comment by MortenHofft** [comment]
I've added the stats to the home page in this commit https://github.com/gbif/hp-new-zealand/commit/0fd1341cecc27ad7f743ffb8c0a38ed8d178aeb1

The idea it to change the layout from the standard home layout to a [`compose` type](https://hp-theme.gbif-staging.org/layout/compose). And then specify the individual blocks and their corresponding data source.

Hope that helps getting you started. Else let me know

**Comment by AaronWilton** [comment]
@MortenHofft  - brilliant!  thank you.  I have not worked with Jerkyll so slowly learning as I go...

**Comment by MortenHofft** [comment]
You are very welcome. It is very theme specific so you had no way of knowing even if you were a Jekyll expert. The Jekyll documentation in combination with the theme docs should be a good starting point though, and then I can fill in the missing parts.

**Comment by MortenHofft** [comment]
I notice that the images for the stats have different aspect ratios and size. Specifically the occurrence one is different. That is why they do not align.
