### ISSUE TITLE
Remove country filter and country column

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-new-zealand#20]
Since the site is scoped to only show data from New Zealand, then the filter for country makes little sense. 
https://hp-theme.gbif-staging.org/data-exploration-config#excluded-filters

Similar on the table view, there is no point in showing the country.
https://hp-theme.gbif-staging.org/data-exploration-config#default-columns-in-occurrence-table

There might be other filters that you find make less sense for your audience. E.g. hostingOrganisation, network, publishingCountry. 
Just to say, that it is possible to hide them

**Comment by AaronWilton** [comment]
Awesome - thanks, had missed that info!
