### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-new-zealand#26]
Some pages are fairly long, it is possible to autogenerate a table of content if you wish to. Just insert `toc: true` in the frontmatter

https://hp-theme.gbif-staging.org/examples/toc/
code here https://raw.githubusercontent.com/gbif/jekyll-theme-algae/master/examples/toc.md

**Comment by AaronWilton** [comment]
thanks @MortenHofft  - good idea.  Have done.
