### ISSUE TITLE
filter by type status

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#27]
**Is your feature request related to a problem? Please describe.**
There does not seem to be an ability to filter the occurrence records by typeStatus - but I may have missed it?

**Describe the solution you'd like**
if not available, add the ability to filter the data grid by type status.
(If it is available, can you please tell me how to add.)

**Describe alternatives you've considered**
Eventually, it may be good to be able to develop a specific page that is pre-filtered and laid out to meet this user need more specifically.

**Additional context**
We have had a legislative change that requires regional authorities to consider type localities when developing environmental monitoring and management plans.  They are looking at various solutions obtain and collate this data....  where as I believe this requirement can be meet through the portal & would provide an additional incentive to connect with GBIF.

**Comment by MortenHofft** [comment]
Is this what you mean? https://new-zealand.hp.gbif-staging.org/data/?typeStatus=HOLOTYPE

**Comment by AaronWilton** [comment]
Hi @MortenHofft 
Absolutely!  but was looking to make it always visible if that is possible. 

Is it possible to add select all or invert selection to those dropdown filters?
(If no, then I can raise as a separate issue so can be triaged appropriately & this one can be closed)

**Comment by MortenHofft** [comment]
That isn't possible to, there isn't a invert. Unlike [GBIF.org ](https://www.gbif.org/occurrence/search?basis_of_record=MATERIAL_CITATION&occurrence_status=present) where you can invert your selection for enumerated filters. And yes, please create an issue in gbif/hosted-portals

You can select which filters are there by default. 
https://hp-theme.gbif-staging.org/data-exploration-config#occurrence-filters
```js
occurrence: {
    highlightedFilters: ['collectionCode', 'taxonKey', 'typeStatus'],
  }
```
